api:
  id: "20422986"
  client:
    id: "5f69949050bd4c96816cd15dad07a4b3"
 
emergencyResponse:
  host: emergency-response-sapi-dev-support-1-5iinov.5sc6y6-2.usa-e2.cloudhub.io
  port: "443"
  path: /api
  protocol: HTTPS

ehr:
  host: ehr-sapi-dev-5iinov.5sc6y6-4.usa-e2.cloudhub.io
  port: "443"
  path: /api
  protocol: HTTPS

mq:
  organizationId: "ec0abd5f-2b31-431b-9dc7-f20318c69809"
  environmentId: "0aa0355b-cb13-4999-a601-21cf1ebb5d8d"
  clientId: "a7a20999695c468e85c4590e93b4c95f"