api:
  id: "20413138"
  client:
    id: "5f69949050bd4c96816cd15dad07a4b3"
 
emergencyResponse:
  host: emergency-response-sapi-dev-support-1-5iinov.5sc6y6-2.usa-e2.cloudhub.io
  port: "443"
  path: /api
  protocol: HTTPS

ehr:
  host: ehr-sapi-dev-5iinov.5sc6y6-4.usa-e2.cloudhub.io
  port: "443"
  path: /api
  protocol: HTTPS