api:
  id: "0"
  client:
    id: x
    secret: y
    
emergencyResponse:
  host: localhost
  port: "9081"
  path: /api
  protocol: HTTP

ehr:
  host: localhost
  port: "9082"
  path: /api
  protocol: HTTP

mq:
  organizationId: "ec0abd5f-2b31-431b-9dc7-f20318c69809"
  environmentId: "0aa0355b-cb13-4999-a601-21cf1ebb5d8d"
  clientId: "a7a20999695c468e85c4590e93b4c95f"