api:
  id: "0"
  client:
    id: x
    secret: y
    
emergencyResponse:
  host: localhost
  port: "9081"
  path: /api
  protocol: HTTP

ehr:
  host: localhost
  port: "9082"
  path: /api
  protocol: HTTP